# ==========================================
# ROYAL FACTORY CONFIGURATION
# ==========================================

APP_NAME=Gymshark Store
PACKAGE_NAME=com.royal.gymshark

CLIENT_URL=https://row.gymshark.com/

THEME_COLOR=#FFFFFF
IS_LIGHT_BG=true

ANDROID_OFFLINE=true 
