pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    // 🔥 تغيير الوضع إلى PREFER_SETTINGS لتجنب التعارض
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        
        // 🔐 Facebook Login
        maven {
            url "https://maven.facebook.com/repository"
        }
        
        // 🔐 Microsoft MSAL
        maven {
            url "https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1"
            name "Duo-SDK-Feed"
        }
        maven {
            url "https://maven.microsoft.com/artifactory/public"
        }
        
        // 💳 Braintree / CardinalCommerce
        maven {
            url "https://cardinalcommerceprod.jfrog.io/artifactory/android"
            name "CardinalCommerce"
        }
        
        // 💳 PayPal (JitPack)
        maven {
            url "https://jitpack.io"
        }
    }
}

rootProject.name = "TWA-mra"
include ':app'
