pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        
        // 💳 Braintree / CardinalCommerce (بيانات الاعتماد مطلوبة)
        maven {
            url "https://cardinalcommerceprod.jfrog.io/artifactory/android"
            name "CardinalCommerce"
            credentials {
                username = 'braintree_team_sdk'
                password = 'AKCp8jQcoDy2hxSWhDAUQKXLDPDx6NYRkqrgFLRc3qDrayg6rrCbJpsKKyMwaykVL8FWusJpp'
            }
        }
        
        // 💳 PayPal (بعض الإصدارات موجودة في JitPack)
        maven {
            url "https://jitpack.io"
        }
    }
}

rootProject.name = "TWA-mra"
include ':app'
